echo "running JITD shell script for 5"
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_3604.jitd > output/policy_act_for/policy_act_for_52_3604_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_3203.jitd > output/policy_act_for/policy_act_for_52_3203_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2802.jitd > output/policy_act_for/policy_act_for_52_2802_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2401.jitd > output/policy_act_for/policy_act_for_52_2401_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2000.jitd > output/policy_act_for/policy_act_for_52_2000_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_1599.jitd > output/policy_act_for/policy_act_for_52_1599_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_1198.jitd > output/policy_act_for/policy_act_for_52_1198_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_10^5_done_uniform.jitd > output/policy_act_for/policy_act_for_52_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_4005.jitd > output/policy_act_for/policy_act_for_52_4005
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_8010.jitd > output/policy_act_for/policy_act_for_52_8010
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_12015.jitd > output/policy_act_for/policy_act_for_52_12015
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_16020.jitd > output/policy_act_for/policy_act_for_52_16020
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_20025.jitd > output/policy_act_for/policy_act_for_52_20025
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_24030.jitd > output/policy_act_for/policy_act_for_52_24030
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_28035.jitd > output/policy_act_for/policy_act_for_52_28035
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_32040.jitd > output/policy_act_for/policy_act_for_52_32040
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_36045.jitd > output/policy_act_for/policy_act_for_52_36045
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_3604.jitd > output/policy_act_for/policy_act_for_53_3604_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_3203.jitd > output/policy_act_for/policy_act_for_53_3203_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2802.jitd > output/policy_act_for/policy_act_for_53_2802_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2401.jitd > output/policy_act_for/policy_act_for_53_2401_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2000.jitd > output/policy_act_for/policy_act_for_53_2000_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_1599.jitd > output/policy_act_for/policy_act_for_53_1599_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_1198.jitd > output/policy_act_for/policy_act_for_53_1198_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_10^5_done_uniform.jitd > output/policy_act_for/policy_act_for_53_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_4005.jitd > output/policy_act_for/policy_act_for_53_4005
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_8010.jitd > output/policy_act_for/policy_act_for_53_8010
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_12015.jitd > output/policy_act_for/policy_act_for_53_12015
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_16020.jitd > output/policy_act_for/policy_act_for_53_16020
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_20025.jitd > output/policy_act_for/policy_act_for_53_20025
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_24030.jitd > output/policy_act_for/policy_act_for_53_24030
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_28035.jitd > output/policy_act_for/policy_act_for_53_28035
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_32040.jitd > output/policy_act_for/policy_act_for_53_32040
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_36045.jitd > output/policy_act_for/policy_act_for_53_36045
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_3604.jitd > output/policy_act_for/policy_act_for_54_3604_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_3203.jitd > output/policy_act_for/policy_act_for_54_3203_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2802.jitd > output/policy_act_for/policy_act_for_54_2802_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2401.jitd > output/policy_act_for/policy_act_for_54_2401_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_2000.jitd > output/policy_act_for/policy_act_for_54_2000_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_1599.jitd > output/policy_act_for/policy_act_for_54_1599_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_1198.jitd > output/policy_act_for/policy_act_for_54_1198_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_10^5_done_uniform.jitd > output/policy_act_for/policy_act_for_54_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_4005.jitd > output/policy_act_for/policy_act_for_54_4005
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_8010.jitd > output/policy_act_for/policy_act_for_54_8010
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_12015.jitd > output/policy_act_for/policy_act_for_54_12015
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_16020.jitd > output/policy_act_for/policy_act_for_54_16020
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_20025.jitd > output/policy_act_for/policy_act_for_54_20025
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_24030.jitd > output/policy_act_for/policy_act_for_54_24030
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_28035.jitd > output/policy_act_for/policy_act_for_54_28035
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_32040.jitd > output/policy_act_for/policy_act_for_54_32040
./driver -j test/policy_act_for_tests/policy_act_for_5/policy_act_for_36045.jitd > output/policy_act_for/policy_act_for_54_36045
echo "running JITD shell script for 6"
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_362.jitd > output/policy_act_for/policy_act_for_62_362_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_322.jitd > output/policy_act_for/policy_act_for_62_322_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_282.jitd > output/policy_act_for/policy_act_for_62_282_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_242.jitd > output/policy_act_for/policy_act_for_62_242_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_202.jitd > output/policy_act_for/policy_act_for_62_202_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_162.jitd > output/policy_act_for/policy_act_for_62_162_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_122.jitd > output/policy_act_for/policy_act_for_62_122_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_10^6_done_uniform.jitd > output/policy_act_for/policy_act_for_62_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_402.jitd > output/policy_act_for/policy_act_for_62_402
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_804.jitd > output/policy_act_for/policy_act_for_62_804
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_1206.jitd > output/policy_act_for/policy_act_for_62_1206
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_1608.jitd > output/policy_act_for/policy_act_for_62_1608
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2010.jitd > output/policy_act_for/policy_act_for_62_2010
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2412.jitd > output/policy_act_for/policy_act_for_62_2412
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2814.jitd > output/policy_act_for/policy_act_for_62_2814
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_3216.jitd > output/policy_act_for/policy_act_for_62_3216
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_3618.jitd > output/policy_act_for/policy_act_for_62_3618
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_362.jitd > output/policy_act_for/policy_act_for_63_362_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_322.jitd > output/policy_act_for/policy_act_for_63_322_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_282.jitd > output/policy_act_for/policy_act_for_63_282_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_242.jitd > output/policy_act_for/policy_act_for_63_242_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_202.jitd > output/policy_act_for/policy_act_for_63_202_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_162.jitd > output/policy_act_for/policy_act_for_63_162_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_122.jitd > output/policy_act_for/policy_act_for_63_122_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_10^6_done_uniform.jitd > output/policy_act_for/policy_act_for_63_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_402.jitd > output/policy_act_for/policy_act_for_63_402
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_804.jitd > output/policy_act_for/policy_act_for_63_804
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_1206.jitd > output/policy_act_for/policy_act_for_63_1206
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_1608.jitd > output/policy_act_for/policy_act_for_63_1608
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2010.jitd > output/policy_act_for/policy_act_for_63_2010
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2412.jitd > output/policy_act_for/policy_act_for_63_2412
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2814.jitd > output/policy_act_for/policy_act_for_63_2814
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_3216.jitd > output/policy_act_for/policy_act_for_63_3216
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_3618.jitd > output/policy_act_for/policy_act_for_63_3618
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_362.jitd > output/policy_act_for/policy_act_for_64_362_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_322.jitd > output/policy_act_for/policy_act_for_64_322_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_282.jitd > output/policy_act_for/policy_act_for_64_282_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_242.jitd > output/policy_act_for/policy_act_for_64_242_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_202.jitd > output/policy_act_for/policy_act_for_64_202_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_162.jitd > output/policy_act_for/policy_act_for_64_162_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_122.jitd > output/policy_act_for/policy_act_for_64_122_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_10^6_done_uniform.jitd > output/policy_act_for/policy_act_for_64_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_402.jitd > output/policy_act_for/policy_act_for_64_402
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_804.jitd > output/policy_act_for/policy_act_for_64_804
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_1206.jitd > output/policy_act_for/policy_act_for_64_1206
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_1608.jitd > output/policy_act_for/policy_act_for_64_1608
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2010.jitd > output/policy_act_for/policy_act_for_64_2010
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2412.jitd > output/policy_act_for/policy_act_for_64_2412
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_2814.jitd > output/policy_act_for/policy_act_for_64_2814
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_3216.jitd > output/policy_act_for/policy_act_for_64_3216
./driver -j test/policy_act_for_tests/policy_act_for_6/policy_act_for_3618.jitd > output/policy_act_for/policy_act_for_64_3618
echo "running JITD shell script for 7"
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_35.jitd > output/policy_act_for/policy_act_for_72_35_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_31.jitd > output/policy_act_for/policy_act_for_72_31_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_27.jitd > output/policy_act_for/policy_act_for_72_27_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_23.jitd > output/policy_act_for/policy_act_for_72_23_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_19.jitd > output/policy_act_for/policy_act_for_72_19_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_15.jitd > output/policy_act_for/policy_act_for_72_15_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_11.jitd > output/policy_act_for/policy_act_for_72_11_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_10^7_done_uniform.jitd > output/policy_act_for/policy_act_for_72_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_39.jitd > output/policy_act_for/policy_act_for_72_39
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_78.jitd > output/policy_act_for/policy_act_for_72_78
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_117.jitd > output/policy_act_for/policy_act_for_72_117
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_156.jitd > output/policy_act_for/policy_act_for_72_156
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_195.jitd > output/policy_act_for/policy_act_for_72_195
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_234.jitd > output/policy_act_for/policy_act_for_72_234
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_273.jitd > output/policy_act_for/policy_act_for_72_273
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_312.jitd > output/policy_act_for/policy_act_for_72_312
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_351.jitd > output/policy_act_for/policy_act_for_72_351
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_35.jitd > output/policy_act_for/policy_act_for_73_35_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_31.jitd > output/policy_act_for/policy_act_for_73_31_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_27.jitd > output/policy_act_for/policy_act_for_73_27_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_23.jitd > output/policy_act_for/policy_act_for_73_23_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_19.jitd > output/policy_act_for/policy_act_for_73_19_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_15.jitd > output/policy_act_for/policy_act_for_73_15_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_11.jitd > output/policy_act_for/policy_act_for_73_11_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_10^7_done_uniform.jitd > output/policy_act_for/policy_act_for_73_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_39.jitd > output/policy_act_for/policy_act_for_73_39
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_78.jitd > output/policy_act_for/policy_act_for_73_78
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_117.jitd > output/policy_act_for/policy_act_for_73_117
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_156.jitd > output/policy_act_for/policy_act_for_73_156
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_195.jitd > output/policy_act_for/policy_act_for_73_195
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_234.jitd > output/policy_act_for/policy_act_for_73_234
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_273.jitd > output/policy_act_for/policy_act_for_73_273
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_312.jitd > output/policy_act_for/policy_act_for_73_312
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_351.jitd > output/policy_act_for/policy_act_for_73_351
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_35.jitd > output/policy_act_for/policy_act_for_74_35_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_31.jitd > output/policy_act_for/policy_act_for_74_31_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_27.jitd > output/policy_act_for/policy_act_for_74_27_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_23.jitd > output/policy_act_for/policy_act_for_74_23_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_19.jitd > output/policy_act_for/policy_act_for_74_19_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_15.jitd > output/policy_act_for/policy_act_for_74_15_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_11.jitd > output/policy_act_for/policy_act_for_74_11_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_10^7_done_uniform.jitd > output/policy_act_for/policy_act_for_74_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_39.jitd > output/policy_act_for/policy_act_for_74_39
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_78.jitd > output/policy_act_for/policy_act_for_74_78
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_117.jitd > output/policy_act_for/policy_act_for_74_117
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_156.jitd > output/policy_act_for/policy_act_for_74_156
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_195.jitd > output/policy_act_for/policy_act_for_74_195
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_234.jitd > output/policy_act_for/policy_act_for_74_234
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_273.jitd > output/policy_act_for/policy_act_for_74_273
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_312.jitd > output/policy_act_for/policy_act_for_74_312
./driver -j test/policy_act_for_tests/policy_act_for_7/policy_act_for_351.jitd > output/policy_act_for/policy_act_for_74_351
echo "running JITD shell script for 8"
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_25.jitd > output/policy_act_for/policy_act_for_81_25
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_30.jitd > output/policy_act_for/policy_act_for_81_30
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_35.jitd > output/policy_act_for/policy_act_for_81_35
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_40.jitd > output/policy_act_for/policy_act_for_81_40
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_45.jitd > output/policy_act_for/policy_act_for_81_45
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_1.jitd > output/policy_act_for/policy_act_for_82_1_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_3.jitd > output/policy_act_for/policy_act_for_82_3_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_10^8_done_uniform.jitd > output/policy_act_for/policy_act_for_82_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_5.jitd > output/policy_act_for/policy_act_for_82_5
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_10.jitd > output/policy_act_for/policy_act_for_82_10
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_15.jitd > output/policy_act_for/policy_act_for_82_15
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_20.jitd > output/policy_act_for/policy_act_for_82_20
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_25.jitd > output/policy_act_for/policy_act_for_82_25
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_30.jitd > output/policy_act_for/policy_act_for_82_30
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_35.jitd > output/policy_act_for/policy_act_for_82_35
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_40.jitd > output/policy_act_for/policy_act_for_82_40
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_45.jitd > output/policy_act_for/policy_act_for_82_45
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_1.jitd > output/policy_act_for/policy_act_for_83_1_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_3.jitd > output/policy_act_for/policy_act_for_83_3_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_10^8_done_uniform.jitd > output/policy_act_for/policy_act_for_83_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_5.jitd > output/policy_act_for/policy_act_for_83_5
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_10.jitd > output/policy_act_for/policy_act_for_83_10
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_15.jitd > output/policy_act_for/policy_act_for_83_15
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_20.jitd > output/policy_act_for/policy_act_for_83_20
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_25.jitd > output/policy_act_for/policy_act_for_83_25
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_30.jitd > output/policy_act_for/policy_act_for_83_30
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_35.jitd > output/policy_act_for/policy_act_for_83_35
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_40.jitd > output/policy_act_for/policy_act_for_83_40
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_45.jitd > output/policy_act_for/policy_act_for_83_45
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_1.jitd > output/policy_act_for/policy_act_for_84_1_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_3.jitd > output/policy_act_for/policy_act_for_84_3_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_10^8_done_uniform.jitd > output/policy_act_for/policy_act_for_84_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_5.jitd > output/policy_act_for/policy_act_for_84_5
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_10.jitd > output/policy_act_for/policy_act_for_84_10
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_15.jitd > output/policy_act_for/policy_act_for_84_15
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_20.jitd > output/policy_act_for/policy_act_for_84_20
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_25.jitd > output/policy_act_for/policy_act_for_84_25
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_30.jitd > output/policy_act_for/policy_act_for_84_30
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_35.jitd > output/policy_act_for/policy_act_for_84_35
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_40.jitd > output/policy_act_for/policy_act_for_84_40
./driver -j test/policy_act_for_tests/policy_act_for_8/policy_act_for_45.jitd > output/policy_act_for/policy_act_for_84_45
echo "running JITD shell script for 9"
./driver -j test/policy_act_for_tests/policy_act_for_9/policy_act_for_10^9_done_uniform.jitd > output/policy_act_for/policy_act_for_91_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_9/policy_act_for_1.jitd > output/policy_act_for/policy_act_for_91_1
./driver -j test/policy_act_for_tests/policy_act_for_9/policy_act_for_10^9_done_uniform.jitd > output/policy_act_for/policy_act_for_92_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_9/policy_act_for_1.jitd > output/policy_act_for/policy_act_for_92_1
./driver -j test/policy_act_for_tests/policy_act_for_9/policy_act_for_10^9_done_uniform.jitd > output/policy_act_for/policy_act_for_93_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_9/policy_act_for_1.jitd > output/policy_act_for/policy_act_for_93_1
./driver -j test/policy_act_for_tests/policy_act_for_9/policy_act_for_10^9_done_uniform.jitd > output/policy_act_for/policy_act_for_94_uniform_result
./driver -j test/policy_act_for_tests/policy_act_for_9/policy_act_for_1.jitd > output/policy_act_for/policy_act_for_94_1
