echo "running all 7 until_done tests"
./driver -j test/Staged_Transforms/divide_6_100.jitd > output/Staged_Transforms/divide_6_100
./driver -j test/Staged_Transforms/divide_6_200.jitd > output/Staged_Transforms/divide_6_200
./driver -j test/Staged_Transforms/divide_6_300.jitd > output/Staged_Transforms/divide_6_300
./driver -j test/Staged_Transforms/divide_6_400.jitd > output/Staged_Transforms/divide_6_400
./driver -j test/Staged_Transforms/divide_6_500.jitd > output/Staged_Transforms/divide_6_500
./driver -j test/Staged_Transforms/divide_6_600.jitd > output/Staged_Transforms/divide_6_600
./driver -j test/Staged_Transforms/divide_6_700.jitd > output/Staged_Transforms/divide_6_700
./driver -j test/Staged_Transforms/divide_6_800.jitd > output/Staged_Transforms/divide_6_800
./driver -j test/Staged_Transforms/divide_6_900.jitd > output/Staged_Transforms/divide_6_900
./driver -j test/Staged_Transforms/divide_6_1000.jitd > output/Staged_Transforms/divide_6_1000
./driver -j test/Staged_Transforms/divide_6_2000.jitd > output/Staged_Transforms/divide_6_2000
./driver -j test/Staged_Transforms/divide_6_until_done.jitd > output/Staged_Transforms/divide_6_until_done
./driver -j test/Staged_Transforms/dividecrack_6_100.jitd > output/Staged_Transforms/dividecrack_6_100
./driver -j test/Staged_Transforms/dividecrack_6_200.jitd > output/Staged_Transforms/dividecrack_6_200
./driver -j test/Staged_Transforms/dividecrack_6_300.jitd > output/Staged_Transforms/dividecrack_6_300
./driver -j test/Staged_Transforms/dividecrack_6_400.jitd > output/Staged_Transforms/dividecrack_6_400
./driver -j test/Staged_Transforms/dividecrack_6_500.jitd > output/Staged_Transforms/dividecrack_6_500
./driver -j test/Staged_Transforms/dividecrack_6_600.jitd > output/Staged_Transforms/dividecrack_6_600
./driver -j test/Staged_Transforms/dividecrack_6_700.jitd > output/Staged_Transforms/dividecrack_6_700
./driver -j test/Staged_Transforms/dividecrack_6_800.jitd > output/Staged_Transforms/dividecrack_6_800
./driver -j test/Staged_Transforms/dividecrack_6_900.jitd > output/Staged_Transforms/dividecrack_6_900
./driver -j test/Staged_Transforms/dividecrack_6_1000.jitd > output/Staged_Transforms/dividecrack_6_1000
./driver -j test/Staged_Transforms/dividecrack_6_2000.jitd > output/Staged_Transforms/dividecrack_6_2000
./driver -j test/Staged_Transforms/dividecrack_6_until_done.jitd > output/Staged_Transforms/dividecrack_6_until_done
./driver -j test/Staged_Transforms/dividecracksort_6_100.jitd > output/Staged_Transforms/dividecracksort_6_100
./driver -j test/Staged_Transforms/dividecracksort_6_200.jitd > output/Staged_Transforms/dividecracksort_6_200
./driver -j test/Staged_Transforms/dividecracksort_6_300.jitd > output/Staged_Transforms/dividecracksort_6_300
./driver -j test/Staged_Transforms/dividecracksort_6_400.jitd > output/Staged_Transforms/dividecracksort_6_400
./driver -j test/Staged_Transforms/dividecracksort_6_500.jitd > output/Staged_Transforms/dividecracksort_6_500
./driver -j test/Staged_Transforms/dividecracksort_6_600.jitd > output/Staged_Transforms/dividecracksort_6_600
./driver -j test/Staged_Transforms/dividecracksort_6_700.jitd > output/Staged_Transforms/dividecracksort_6_700
./driver -j test/Staged_Transforms/dividecracksort_6_800.jitd > output/Staged_Transforms/dividecracksort_6_800
./driver -j test/Staged_Transforms/dividecracksort_6_900.jitd > output/Staged_Transforms/dividecracksort_6_900
./driver -j test/Staged_Transforms/dividecracksort_6_1000.jitd > output/Staged_Transforms/dividecracksort_6_1000
./driver -j test/Staged_Transforms/dividecracksort_6_2000.jitd > output/Staged_Transforms/dividecracksort_6_2000
./driver -j test/Staged_Transforms/dividecracksort_6_until_done.jitd > output/Staged_Transforms/dividecracksort_6_until_done
./driver -j test/Staged_Transforms/dcsm_6_100.jitd > output/Staged_Transforms/dcsm_6_100
./driver -j test/Staged_Transforms/dcsm_6_200.jitd > output/Staged_Transforms/dcsm_6_200
./driver -j test/Staged_Transforms/dcsm_6_300.jitd > output/Staged_Transforms/dcsm_6_300
./driver -j test/Staged_Transforms/dcsm_6_400.jitd > output/Staged_Transforms/dcsm_6_400
./driver -j test/Staged_Transforms/dcsm_6_500.jitd > output/Staged_Transforms/dcsm_6_500
./driver -j test/Staged_Transforms/dcsm_6_600.jitd > output/Staged_Transforms/dcsm_6_600
./driver -j test/Staged_Transforms/dcsm_6_700.jitd > output/Staged_Transforms/dcsm_6_700
./driver -j test/Staged_Transforms/dcsm_6_800.jitd > output/Staged_Transforms/dcsm_6_800
./driver -j test/Staged_Transforms/dcsm_6_900.jitd > output/Staged_Transforms/dcsm_6_900
./driver -j test/Staged_Transforms/dcsm_6_1000.jitd > output/Staged_Transforms/dcsm_6_1000
./driver -j test/Staged_Transforms/dcsm_6_2000.jitd > output/Staged_Transforms/dcsm_6_2000
./driver -j test/Staged_Transforms/dcsm_6_until_done.jitd > output/Staged_Transforms/dcsm_6_until_done